version: '3.4'
services:

  #########################
  # DATABASE
  #########################
  
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - 5433:${DB_PORT}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "auction_db", "-U", "auction" ]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - backend_network

#########################
# Django app
#########################
  
  backend:
    build: 
      context: ./backend/
      target: prod
    restart: always
    container_name: backend
    command: bash -c "python /app/manage.py collectstatic --noinput && gunicorn auction_backend.wsgi:application --bind 0.0.0.0:$APP_PORT --access-logfile -"
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    volumes:
      - ./volumes/staticfiles:/app/static
      - ./volumes/media:/app/media
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env
    networks:
      - backend_network
    depends_on:
      - postgres

#########################
# Nginx
#########################

  nginx:
    build:
      context: ./nginx/
      target: base
    restart: always
    container_name: nginx
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/staticfiles:/static
      - ./volumes/media:/media
    networks:
      - backend_network  

networks:
  backend_network:
    driver: bridge